name: Build Godot Project
description: "Builds a Godot project for Windows"
author: "Daniel Konar"

runs:
  using: "composite"
  steps:
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: ${{ inputs.godot-version }}
        use-dotnet: false
        include-templates: true
    - name: Reimport
      shell: bash
      id: reimport
      run: godot --editor --headless --quit || true

    - name: Build
      id: build
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: |
        mkdir -p ${{ inputs.build-dir }}/${{ inputs.platform-name }}
        godot --export-debug "${{ inputs.export-preset }}" --headless

    - name: Compress Build Output
      id: compress
      shell: pwsh
      working-directory: ${{ inputs.project-dir }}
      run: |
        $zipPath = "${{ inputs.build-dir }}/${{ inputs.platform-name }}/${{ inputs.project-name }}-${{ inputs.platform-name }}.zip"
        $sourcePath = "${{ inputs.build-dir }}/${{ inputs.platform-name }}"
        Compress-Archive -Path $sourcePath\* -DestinationPath $zipPath -Force

    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.project-name }}-${{ inputs.platform-name }}
        path: ${{ inputs.project-dir }}/${{ inputs.build-dir }}/${{ inputs.platform-name }}/${{ inputs.project-name }}-${{ inputs.platform-name }}.zip

inputs:
  godot-version:
    description: "Godot version to use"
    required: false
    default: "4.7.1"
  project-dir:
    description: "Project directory"
    required: true
  build-dir:
    description: "Build directory (relative to project-dir)"
    required: false
    default: "build"
  export-preset:
    description: "Export preset name"
    required: false
    default: "Windows"
  platform-name:
    description: "Platform name for artifacts and directories"
    required: false
    default: "windows-x86_64"
  project-name:
    description: "Project name"
    required: false
    default: "Realmz-Remake"
