name: "Submit Dev"

on:
  push:
    branches: ["dev"]

env:
  GODOT_VERSION: 4.3
  PROJECT_FILE: src/project.godot
  VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*
  LFS_USERNAME: ${{secrets.LFS_USERNAME}}
  LFS_PASSWORD: ${{secrets.LFS_PASSWORD}}

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Install Godot
        uses: ./.github/actions/install-godot-macos
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Open Godot editor for reimport
        run: ${{ steps.install-godot.outputs.godot-executable }} --editor --headless --quit || true

      - name: Build and upload artifacts for macOS
        uses: ./.github/actions/build-godot-macos
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
          project-dir: "./src"
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Build and upload artifacts for linux
        uses: ./.github/actions/build-godot-linux
        with:
          project-dir: "./src"
  build-raspberry-pi:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Install Godot
        uses: ./.github/actions/install-godot-raspberry-pi
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Build and upload artifacts for raspberry pi
        uses: ./.github/actions/build-godot-raspberry-pi
        with:
          project-dir: "./src"
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Build and upload artifacts for windows
        uses: ./.github/actions/build-godot-windows
        with:
          project-dir: "./src"

  generate-release:
    needs: [build-windows, build-raspberry-pi, build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Extract version
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.PROJECT_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: Realmz-Remake-macos
          path: artifacts/Realmz-Remake-macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Realmz-Remake-windows-x86_64
          path: artifacts/Realmz-Remake-windows-x86_64

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: Realmz-Remake-linux-x86_64
          path: artifacts/Realmz-Remake-linux-x86_64

      - name: Download Linux aarch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Realmz-Remake-linux-aarch64
          path: artifacts/Realmz-Remake-linux-aarch64

      - name: Tag and upload artifacts to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-version.outputs.version-string }}
          commit: ${{ github.sha }}
          allowUpdates: false
          artifactErrorsFailBuild: true
          prerelease: true
          artifacts: artifacts/*/*
