name: "Verify Dev"

on:
  pull_request:
    branches: ["dev"]

env:
  GODOT_VERSION: 4.3
  PROJECT_FILE: src/project.godot
  VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*
  LFS_USERNAME: ${{secrets.LFS_USERNAME}}
  LFS_PASSWORD: ${{secrets.LFS_PASSWORD}}

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Extract old version string
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.PROJECT_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version-old

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Extract new version string
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.PROJECT_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version-new

      - name: Check semantic version bump
        uses: CapsCollective/version-actions/check-version-bump@v1.0
        with:
          new-version: ${{ steps.extract-version-new.outputs.version-string }}
          old-version: ${{ steps.extract-version-old.outputs.version-string }}

  # run-project-validation:
  #   needs: check-version-bump
  #   runs-on: macos-13
  #   steps:
  #     - name: Checkout current branch
  #       uses: actions/checkout@v4

  #     - name: Install Godot
  #       uses: ./.github/actions/install-godot-macos
  #       with:
  #         godot-version: ${{ env.GODOT_VERSION }}
  #       id: install-godot

  #     - name: Open Godot editor for reimport
  #       run: ${{ steps.install-godot.outputs.godot-executable }} --editor --headless --quit || true

  #     # disabled as we dont have any validation scripts, yet
  #     - name: Run project validations
  #       if: false
  #       run: ${{ steps.install-godot.outputs.godot-executable }} --script scripts/run_validations.gd --headless

  build-macos:
    needs: check-version-bump
    runs-on: macos-13
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Install Godot
        uses: ./.github/actions/install-godot-macos
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Open Godot editor for reimport
        run: ${{ steps.install-godot.outputs.godot-executable }} --editor --headless --quit || true

      - name: Build and upload artifacts for macOS
        uses: ./.github/actions/build-godot-macos
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
          project-dir: "./src"
  build-linux:
    needs: check-version-bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Build and upload artifacts for linux
        uses: ./.github/actions/build-godot-linux
        with:
          project-dir: "./src"
          export-preset: "Linux"
  build-windows:
    needs: check-version-bump
    runs-on: windows-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Configure Git LFS
        run: git config -f .lfsconfig lfs.url https://${{env.LFS_USERNAME}}:${{env.LFS_PASSWORD}}@git-lfs-s3-proxy-984.pages.dev/c8076907f522754d603bf3b68096609c.r2.cloudflarestorage.com/realmz-remake

      - name: Checkout LFS
        run: git lfs fetch --all && git lfs checkout

      - name: Build and upload artifacts for windows
        uses: ./.github/actions/build-godot-linux
        with:
          project-dir: "./src"
          export-preset: "Windows"
          platform-name: "windows-x86_64"
